# ----
# Site

title: SUBJPOP
url: "https://subjpop.com"
baseurl:
google_analytics_key: UA-98703426-2
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: The homepage of SUBJPOP, a podcast of semi-alternative Japanese pop music bi(?)weekly
author:
  name: Yifan
  email: subjpop@gmail.com
  website: "ivanwoo.github.io"
  twitter: # twitter username without the @ symbol
social:
  name:
  links:

# Values for the sc_player gem (https://github.com/itsbrnrd/jekyll_sc_player/blob/master/sc_player.rb)
sc_player:
  auto_play: false
  buying: false
  liking: true
  download: true
  sharing: true
  show_artwork: true
  show_comments: true
  show_playcount: true
  show_user: true
  start_track: 0

# -----
# Build

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: false
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true
  -
    scope:
      path: "about.html"
    values:
      layout: "default-sakura"
  -
    scope:
      path: "podcast-rss.md"
    values:
      layout: "podcast-rss"
  -
    scope:
      path: "2017-ranking.html"
    values:
      layout: "book-reader"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# Misc
licence: CC-BY-CA
# Podcast
podcast:
  title: SUBJPOP
  art: /images/favicon.png
  category: Music
  subtitle: SUBJPOP is a podcast of semi-alternative Japanese pop music bi(?)weekly.
  summary: >
    SUBJPOP is a podcast of semi-alternative Japanese pop music bi(?)weekly.