# ----
# Site

title: Sub J-Pop
url: "https://subjpop.github.io/"
baseurl:
google_analytics_key: UA-98703426-2
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: The homepage of Sub J-Pop, a podcast of semi-alternative Japanese pop music bi(?)weekly
author:
  name: subjpop
  email: subjpop@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name:
  links:

# Values for the sc_player gem (https://github.com/itsbrnrd/jekyll_sc_player/blob/master/sc_player.rb)
sc_player:
  auto_play: false
  buying: false
  liking: true
  download: true
  sharing: true
  show_artwork: true
  show_comments: true
  show_playcount: true
  show_user: true
  start_track: 0

# -----
# Build

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

